### ISSUE TITLE
How translate this part

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#497]
![screenshot_2015-06-19-00-29-51](https://cloud.githubusercontent.com/assets/428820/8247663/9788ee70-161a-11e5-92c1-962f63d0ea64.png)

**Transcripts for the modern internet**
and
**::SayIt**
tnks

**Comment by dracos** [comment]
I have pushed new .po files containing those strings for translation, thanks.

**Comment by johnfelipe** [comment]
Where?, in transifex?, please tell me where for translate it, tnks

**Comment by dracos** [comment]
Pushed to github in the master branch of both <a href="https://github.com/mysociety/sayit/tree/master/speeches/locale">sayit</a> and <a href="https://github.com/mysociety/sayit.mysociety.org/tree/master/sayit_mysociety_org/locale">sayit.mysociety.org</a>, and now pushed to Transifex also.

**Comment by johnfelipe** [comment]
![continues](https://cloud.githubusercontent.com/assets/428820/8263206/2423e3de-169e-11e5-8d56-e96d04fb9f57.png)

**Transcripts for the modern internet**
Still show it

**Comment by johnfelipe** [comment]
It work>

![work](https://cloud.githubusercontent.com/assets/428820/8263957/0345f636-16a6-11e5-99d2-cab4a8573c05.png)
